#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=01

CONFIGURATION=wake_host_shell

start_service() {
    # Reading config
    config_load "${CONFIGURATION}"
    local listen_interface
    local listen_dns
    local host_mac
 
    config_get listen_interface Host listen_interface
    config_get listen_dns Host listen_dns
    config_get host_mac Host host_mac

    procd_open_instance
    procd_set_param nice 19
    procd_set_param command "/usr/bin/wake_host.sh" "$listen_interface" "$listen_dns" "$host_mac"
    procd_set_param file /etc/config/wake_host_shell
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
